/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/r3xHzjlJpBh
 */
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div className="bg-white p-6 rounded-lg shadow-md w-full max-w-md mx-auto">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold">Give Feedback</h2>
        <button aria-label="Close">
          <XIcon className="h-6 w-6" />
        </button>
      </div>
      <p className="mb-4 font-medium">We'd love to hear from you. How are you feeling about Slack?</p>
      <form>
        <div className="space-y-2 mb-4">
          <label className="flex items-center space-x-2">
            <input className="rounded" type="checkbox" />
            <span>I can't find something.</span>
          </label>
          <label className="flex items-center space-x-2">
            <input className="rounded" type="checkbox" />
            <span>I can't figure out how to do something.</span>
          </label>
          <label className="flex items-center space-x-2">
            <input className="rounded" type="checkbox" />
            <span>I figured out how to do something, but it was too hard to do.</span>
          </label>
          <label className="flex items-center space-x-2">
            <input className="rounded" type="checkbox" />
            <span>I love it!</span>
          </label>
          <label className="flex items-center space-x-2">
            <input className="rounded" type="checkbox" />
            <span>Something else.</span>
          </label>
        </div>
        <div className="mb-4">
          <label className="block mb-2 font-medium" htmlFor="feedback">
            Anything else you'd like to share?
          </label>
          <textarea
            className="w-full p-2 border border-gray-200 rounded dark:border-gray-800"
            id="feedback"
            placeholder="I have feedback on..."
            rows="4" />
        </div>
        <div className="flex justify-between items-center">
          <a className="text-sm text-blue-600 hover:underline" href="#">
            Privacy Policy
          </a>
          <div className="space-x-2">
            <Button variant="outline">Cancel</Button>
            <Button>Submit</Button>
          </div>
        </div>
      </form>
    </div>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 18" />
      <path d="m6 6 12" />
    </svg>)
  );
}
